import { ThemeConfig } from './types';

export const themes: Record<string, ThemeConfig> = {
  canopy: {
    name: 'canopy',
    label: 'Timberline Canopy (PNW)',
    light: {
      bg: '#F2F4F1',
      surface: '#E5EAE4',
      text: '#14231C',
      primary: '#2D5A43',
      muted: '#5E8C6A',
      fontHeader: '"Plus Jakarta Sans", "Inter", sans-serif',
      fontBody: '"Inter", sans-serif',
    },
    dark: {
      bg: '#0B100D',
      surface: '#131C18',
      text: '#E4EAE6',
      primary: '#4A8B64',
      muted: '#7A9385',
      fontHeader: '"Plus Jakarta Sans", "Inter", sans-serif',
      fontBody: '"Inter", sans-serif',
    },
  },
  monolith: {
    name: 'monolith',
    label: 'Haystack Monolith (PNW)',
    light: {
      bg: '#EFECE6',
      surface: '#E2DDD5',
      text: '#1E252B',
      primary: '#3A525C',
      muted: '#6B7F88',
      fontHeader: '"Space Grotesk", sans-serif',
      fontBody: 'system-ui, -apple-system, sans-serif',
    },
    dark: {
      bg: '#11161A',
      surface: '#1A2127',
      text: '#ECEFF1',
      primary: '#527987',
      muted: '#90A4AE',
      fontHeader: '"Space Grotesk", sans-serif',
      fontBody: 'system-ui, -apple-system, sans-serif',
    },
  },
  basalt: {
    name: 'basalt',
    label: 'Alvord Basalt (PNW)',
    light: {
      bg: '#EAEAEA',
      surface: '#DDDDDD',
      text: '#121212',
      primary: '#C26D09',
      muted: '#666666',
      fontHeader: '"Geist", "Geist Sans", sans-serif',
      fontBody: '"Geist Mono", monospace',
    },
    dark: {
      bg: '#090909',
      surface: '#161616',
      text: '#E4E4E7',
      primary: '#F59E0B',
      muted: '#71717A',
      fontHeader: '"Geist", "Geist Sans", sans-serif',
      fontBody: '"Geist Mono", monospace',
    },
  },
  blueprint: {
    name: 'blueprint',
    label: 'Blueprint Core',
    light: {
      bg: '#E1E8ED',
      surface: '#F5F8FA',
      text: '#1C2127',
      primary: '#106BA3',
      muted: '#5C7080',
      fontHeader: '-apple-system, "Inter", "Segoe UI", sans-serif',
      fontBody: '-apple-system, "Inter", "Segoe UI", sans-serif',
    },
    dark: {
      bg: '#293742',
      surface: '#30404D',
      text: '#F5F8FA',
      primary: '#2B95D6',
      muted: '#8A9BA8',
      fontHeader: '-apple-system, "Inter", "Segoe UI", sans-serif',
      fontBody: '-apple-system, "Inter", "Segoe UI", sans-serif',
    },
  },
};
